In [1]:
import pandas as pd
import sqlite3
from mlxtend.frequent_patterns import apriori,association_rules
import pyodbc

In [2]:
DB2 = {'servername': 'LAPTOP-OGICI52C\\SQLEXPRESS',
       'database': 'AdventureWorks2019'}

export_conn_adventurewors = pyodbc.connect('DRIVER={SQL Server};SERVER='+ DB2['servername'] + ';DATABASE=' + DB2['database'] + ';Trusted_Connection=yes')

In [3]:
adv_df_product = pd.read_sql_query("SELECT * from Production.Product",export_conn_adventurewors)
adv_df_orderdetails = pd.read_sql_query("SELECT * from Purchasing.PurchaseOrderDetail",export_conn_adventurewors)
df = pd.merge(adv_df_orderdetails, adv_df_product, on= 'ProductID')
df

C:\Users\harre\AppData\Local\Temp\ipykernel_24028\959278620.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  adv_df_product = pd.read_sql_query("SELECT * from Production.Product",export_conn_adventurewors)
C:\Users\harre\AppData\Local\Temp\ipykernel_24028\959278620.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  adv_df_orderdetails = pd.read_sql_query("SELECT * from Purchasing.PurchaseOrderDetail",export_conn_adventurewors)

,PurchaseOrderID,PurchaseOrderDetailID,DueDate,OrderQty,ProductID,UnitPrice,LineTotal,ReceivedQty,RejectedQty,StockedQty,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate_y
0,1,1,2011-04-30,4,1,50.2600,201.0400,3.0,0.0,3.0,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
1,80,181,2012-02-23,3,1,50.2635,150.7905,3.0,0.0,3.0,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
2,159,380,2012-06-13,3,1,50.2635,150.7905,3.0,0.0,3.0,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
3,238,562,2012-09-19,3,1,50.2635,150.7905,3.0,0.0,3.0,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
4,317,716,2013-05-08,3,1,50.2635,150.7905,3.0,0.0,3.0,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8840,4011,8841,2014-07-24,1000,880,20.5600,20560.0000,1000.0,0.0,1000.0,...,S,None,None,32.0,107.0,2013-05-30,NaT,None,A99D90C0-05E2-4E44-AD90-C55C9F0784DE,2014-02-08 10:01:36.827
8841,4012,8842,2014-07-24,6000,881,41.5700,249420.0000,6000.0,0.0,6000.0,...,S,None,U,21.0,32.0,2013-05-30,NaT,None,05B2E20F-2399-4CB3-9B49-B28D6649C104,2014-02-08 10:01:36.827
8842,4012,8843,2014-07-24,6000,882,41.5700,249420.0000,6000.0,0.0,6000.0,...,S,None,U,21.0,32.0,2013-05-30,NaT,None,BBBF003B-367D-4D71-AF71-10F50B6234A0,2014-02-08 10:01:36.827
8843,4012,8844,2014-07-24,6000,883,41.5700,249420.0000,6000.0,0.0,6000.0,...,S,None,U,21.0,32.0,2013-05-30,NaT,None,2D9F59B8-9F24-46EB-98AD-553E48BB9DB9,2014-02-08 10:01:36.827
8844,4012,8845,2014-07-24,6000,884,41.5700,249420.0000,6000.0,0.0,6000.0,...,S,None,U,21.0,32.0,2013-05-30,NaT,None,906D42F6-C21F-4D20-B528-02FFDB55FD1E,2014-02-08 10:01:36.827

In [4]:
df_werk = (df[df['MakeFlag'] == False]
           .groupby(['PurchaseOrderDetailID', 'Name'])['OrderQty']
           .sum()
           .unstack()
           .reset_index()
           .fillna(0)
           .set_index('PurchaseOrderDetailID'))
df_werk

Name,AWC Logo Cap,Adjustable Race,All-Purpose Bike Stand,Bearing Ball,Bike Wash - Dissolver,Cable Lock,Chain,Chainring,Chainring Bolts,Chainring Nut,...,Touring Tire,Touring Tire Tube,"Touring-Panniers, Large",Water Bottle - 30 oz.,"Women's Mountain Shorts, L","Women's Mountain Shorts, M","Women's Mountain Shorts, S","Women's Tights, L","Women's Tights, M","Women's Tights, S"
PurchaseOrderDetailID,,,,,,,,,,,,,,,,,,,,,
1,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8844,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
def hot_encode(x):
    try:
        x = float(x)  # Converteer x naar float
    except ValueError:
        return 0  # Of een andere waarde voor niet-numerieke invoer

    if x <= 0:
        return 0
    if x >= 1:
        return 1
    return x

# Pas de functie toe op de gehele DataFrame
basket_encoded = df_werk.applymap(hot_encode)
df = basket_encoded
df

Name,AWC Logo Cap,Adjustable Race,All-Purpose Bike Stand,Bearing Ball,Bike Wash - Dissolver,Cable Lock,Chain,Chainring,Chainring Bolts,Chainring Nut,...,Touring Tire,Touring Tire Tube,"Touring-Panniers, Large",Water Bottle - 30 oz.,"Women's Mountain Shorts, L","Women's Mountain Shorts, M","Women's Mountain Shorts, S","Women's Tights, L","Women's Tights, M","Women's Tights, S"
PurchaseOrderDetailID,,,,,,,,,,,,,,,,,,,,,
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8841,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8842,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8843,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8844,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8845,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Deze regel gebruikt het Apriori-algoritme om frequente itemsets te vinden in de DataFrame df.
# min_support = 0.01 geeft de minimumsupportdrempel aan waaraan een itemset moet voldoen om als frequent te worden beschouwd.
# use_colnames = True geeft aan dat kolomnamen moeten worden gebruikt in de uitvoer DataFrame
frq_items = apriori(df, min_support = 0.01, use_colnames = True)

# Deze regel genereert associatieregels uit de frequente itemsets frq_items.
# De parameter metric geeft aan welke maatstaf moet worden gebruikt om de gegenereerde regels te evalueren, hier is "lift" gekozen.
# min_threshold = 1 stelt de minimumdrempel in voor de evaluatiemaatstaf. In dit geval worden regels met een lift groter dan of gelijk aan 1 beschouwd.
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)

# Deze regel sorteert de gegenereerde associatieregels op twee criteria: confidence en lift.
# ascending =[False, False] geeft aan dat de sorteer volgorde voor zowel confidence als lift aflopend is (van hoog naar laag).
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules

C:\Users\harre\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []